name: CI

# We run CI on every push
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

# Automatically cancel running workflows when there's a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run build

  typecheck:
    name: Typechecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run typecheck

  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
